name: cd-deploy-and-run-code-on-vm
on:
  workflow_run:
    workflows: ["ci-test-actions"]
    branches: [main]
    types: 
      - completed
jobs:
  send-code-zipped:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: zip folder with content
          run: |
            sudo apt install zip unzip
            zip -r tornado_python.zip .

        - name: copy to vm from current runner
          run: |
            sudo apt-get install sshpass
            sudo  sshpass -p ${{ secrets.AZURE_VM_PASSWORD }} scp -o StrictHostKeyChecking=no -v -r tornado_python.zip ${{ secrets.AZURE_VM_USERNAME }}@${{ secrets.AZURE_VM_HOST }}:/home/yael-vm

  unzip-code-on-vm:
      runs-on: ubuntu-latest
      needs: send-code-zipped
      steps:
        - name: executing remote ssh unzip commands using password
          uses: appleboy/ssh-action@v1.0.3
          with:
              host: ${{ secrets.AZURE_VM_HOST }}
              username: ${{ secrets.AZURE_VM_USERNAME }}
              password: ${{ secrets.AZURE_VM_PASSWORD }}
              port: ${{ secrets.AZURE_VM_PORT }}
              script: |
                sudo apt install unzip
                cd /home/yael-vm
                rm -f tornado_python
                mkdir tornado_python
                unzip tornado_python.zip -d ./tornado_python

                cp /home/yael-vm/tornado_python/python-app.service /etc/systemd/system/
                cd /etc/systemd/system/
                sudo systemctl enable python-app.service
                sudo systemctl daemon-reload
                sudo service python-app start

              
                
