name: cd-deploy-and-run-code-on-vm
on:
  push:
    branches:
      - main
jobs:
  send-code-zipped:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: zip folder with content
          run: |
            sudo apt install zip unzip
            pwd
            zip -r tornado_python.zip .

        - name: copy to vm from current runner
          run: |
            sudo apt-get install sshpass
            sudo sshpass -p Yael1234567890
            sudo scp -o StrictHostKeyChecking=no -v -r tornado_python.zip yael-vm@20.127.209.88:/home/yael/apps/
