name: cd-deploy-and-run-code-on-vm
on:
  push:
    branches:
      - main
jobs:
  send-code-zipped:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: zip folder with content
          run: |
            sudo apt install zip unzip
            pwd
            zip -r tornado_python.zip .

        - name: copy to vm from current runner
          run: |
            sudo apt-get install sshpass
            sudo  sshpass -p Yael1234567890 scp -o StrictHostKeyChecking=no -v -r tornado_python.zip yael-vm@20.127.209.88:/home/yael-vm

  unzip-code-on-vm:
      runs-on: ubuntu-latest
      needs: send-code-zipped
      steps:
        - name: uzip folder on vm
          run: |
            sudo apt-get install sshpass
            sudo sshpass -p Yael1234567890 ssh -o StrictHostKeyChecking=no yael-vm@20.127.209.88 
            sudo apt install unzip
            rm -f tornado_python
            mkdir tornado_python
            echo pwd
            unzip tornado_python.zip -d ./tornado_python
        - name: create and run app as a service
          run: |
            cp /home/yael-vm/tornado_python/python-app.service /etc/systemd/system/
            cd /etc/systemd/system/
            sudo systemctl enable python-app.service
            sudo systemctl daemon-reload
            sudo service python-app start


