name: ci-test-actions
run-name: ${{ github.actor }} is testing code
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
        - name: Install dependencies
          run: |
            pip install wheel setuptools pip --upgrade
            pip3 install wheel setuptools pip --upgrade
            pip install -r requirements.txt
        - name: Test with unittest
          run: |
            cd tests
            python -m unittest
