name: ci-test-actions
run-name: ${{ github.actor }} is testing code
on: [push]
jobs:
  check-tests:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: 3.10.11
        - name: Install dependencies
          run: 
             pip install --upgrade pip
             pip install flake8 pytest
             pip install -r requirements.txt
        - name: Test with unittest
          run: |
            cd tests
            python -m unittest
